# Generated by Django 4.2.6 on 2023-10-16 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activeuserapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submmittedtasks',
            old_name='amount_to_paid',
            new_name='amount_to_be_paid_as_reward',
        ),
    ]
