# Generated by Django 4.2.6 on 2023-10-21 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activeuserapp', '0002_rename_amount_to_paid_submmittedtasks_amount_to_be_paid_as_reward'),
    ]

    operations = [
        migrations.AddField(
            model_name='downloadedtask',
            name='uploaded_status',
            field=models.BooleanField(default=False),
        ),
    ]
