# Generated by Django 4.2.5 on 2023-10-07 15:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('paymentapp', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationuser',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='paymentapp.plan'),
        ),
        migrations.AddField(
            model_name='applicationuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='user_accounts_permissions', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
