# Generated by Django 4.2.6 on 2023-10-16 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='total_amount_earned_from_site',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
