# Generated by Django 4.2.6 on 2023-10-11 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paymentapp', '0002_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='date_subscribeed',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
